# Numpy in Python
Load in NumPy (Remember to pip install numpy first)
Numpy is a multi-dimensional array library -> can store all sort of data in one dimensional array, two dimensional array, three dimensional array, etc

faster to read less bytes of memory
why is Numpy faster than Lists:->
    1. It has fixed size
    2. has contiguous memory
    3. No type checking when iterating through objects
    
Applications of Numpy :->
    1. Mathematics
    2. Plotting
    3. Backend
    4. Machine Learning

In [1]:
import numpy as np

# The Basics

In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
b = np.array([[9,8,7],[6,5,4]])
print(b)

[[9 8 7]
 [6 5 4]]


In [3]:
a = np.array([[1,2,3],[4,5,6]])

a.ndim

2

In [4]:
a.shape

(2, 3)

In [5]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
a[0,2] #should print 3

3

In [4]:
#Get dimensions
a.ndim

1

In [5]:
b.ndim

2

In [6]:
#get shape
a.shape

(3,)

In [7]:
b.shape

(2, 3)

In [8]:
#get type
a.dtype

dtype('int32')

# Accessing/changing specific elements, rows,columns,etc

In [9]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [10]:
a.shape

(2, 7)

In [11]:
#get a specific element [r,c]
a[1][6]

14

In [12]:
#get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [13]:
#get a specifc column
a[:,2]

array([ 3, 10])

In [14]:
#getting a little more fancy [startindex : endindex : stepsize]
a[0,1:6:2]

array([2, 4, 6])

In [15]:
#changing a specific element
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


# Initializing Different types of arrays

In [16]:
# all zeros matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [20]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
#all 1s matrix
np.ones((3,3) , dtype='int32')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [24]:
#Any other number
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [25]:
# any other number(full like)
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [26]:
# random decimal numbers
np.random.rand(4,2)

array([[0.67784495, 0.55150864],
       [0.22802223, 0.81999407],
       [0.27426144, 0.34364205],
       [0.24353069, 0.76825165]])

In [29]:
#Random integer values
np.random.randint(100,size=(3,3))

array([[57, 10, 79],
       [83, 88, 29],
       [99, 89, 90]])

In [30]:
#identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# Be careful when copying arrays!!

In [33]:
a = np.array([1,2,3])
b = a 
b[0] = 100
print(b)

print(a) #copying elements can make change to the original matrix

[100   2   3]
[100   2   3]


In [34]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(b)

print(a) 

[100   2   3]
[1 2 3]


# Mathematics

In [35]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [36]:
a+2

array([3, 4, 5, 6])

In [37]:
a-2

array([-1,  0,  1,  2])

In [38]:
a*2

array([2, 4, 6, 8])

In [39]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [40]:
b = np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

# Linear Algebra

In [41]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [43]:
# find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

# Miscellaneous
load data from file

In [48]:
filedata = np.genfromtxt('data.txt',delimiter=',')
filedata.astype('int32')

array([[ 1, 23, 45, 67, 32, 54, 12, 56, 99,  0, 12, 32, 42, 56,  7,  8,
         9,  1, 11, 23],
       [ 6, 85, 45, 99, 12, 34, 56, 78, 99,  1, 58, 97, 13, 49,  1,  9,
         7,  9, 11, 23],
       [ 7, 88, 99, 11, 22, 33, 44, 55, 55,  6, 77, 77, 77, 88,  8,  9,
         1,  1, 10, 45]])